#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use JSON;
use C4::Auth qw/check_api_auth/;
use C4::Reserves;
use Koha::Biblios;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/json', -status => '403 Forbidden');
  print encode_json({status => $status});
  exit 0;
}

my $biblionumber = $query->param('biblionumber');

unless ($biblionumber) {
  print $query->header(-type => 'text/json', -status => '400');
  print encode_json({status => "Biblionumber is required", error_code => "biblionumberIsMissing"});
  exit 0;
}

my $biblio = Koha::Biblios->find( $biblionumber );

unless ($biblio) {
  print $query->header(-type => 'text/json', -status => '400');
  print encode_json({status => "Biblio not found", error_code => "biblioNotFound"});
  exit 0;
}

my $holds = $biblio->holds;
my $reserves = $holds->unblessed;

unless ($reserves) {
  print $query->header(-type => 'text/json', -status => '500');
  print encode_json({status => "Unrecognized error", error_code => "unrecognizedError"});
  exit 0;
}

print $query->header(-type => 'text/json',-charset => 'utf-8');
print encode_json({reserves => $reserves});

exit 0;
