#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use C4::Auth qw/check_api_auth/;
use C4::Members;
use Koha::Patrons;
use XML::Simple;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}
my $cardnumber= $query->url_param('cardnumber');
my $pincode = $query->url_param('pin');
# Allow for the transitional use of the url parameter 'personalnumber' instead of 'pin' (it still contains the pincode)
# Only check this if the 'pin' parameter is not set
if (!$pincode) {
  $pincode = $query->url_param('personalnumber');
}

unless ($cardnumber) {
  print $query->header(-type => 'text/xml', -status => '404');
  print XMLout({ status => "Cardnumber is required", error_code => "cardnumberIsRequired"  }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

unless ($pincode) {
  print $query->header(-type => 'text/xml', -status => '404');
  print XMLout({ status => "Pin is required", error_code => "pinIsRequired"  }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $patrons = Koha::Patrons->search({cardnumber => $cardnumber});
my $borrower = $patrons->next;

my $match = "false";

unless ($borrower) {
  #print $query->header(-type => 'text/xml', -status => '404');
  # print XMLout({ status => "Borrower not found", error_code => "borrowerNotFound"  }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  print $query->header(-type => 'text/xml',-charset => 'utf-8');
  print XMLout({match => $match}, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my $borrowernumber = $borrower->unblessed->{'borrowernumber'};
my $pin = $borrower->get_extended_attribute("PIN");
if ($pin and $pin->attribute eq $pincode) {
  $match = "true";
}

print $query->header(-type => 'text/xml',-charset => 'utf-8');
print XMLout({match => $match}, NoAttr => 1, RootName => 'response', XMLDecl => 1);

exit 0;
