#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use C4::Auth qw/check_api_auth/;
use C4::Members;
use C4::Members::Attributes qw( GetBorrowerAttributeValue );
use Koha::Patrons;
use XML::Simple;
use Data::Dumper;                                                        # DEBUG

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';
print "Content-type: text/plain\n\n";

my $cardnumber= $query->url_param('user');
my $personalnumber = $query->url_param('pass');

unless ($cardnumber) {
    print "0\r\n";
    exit 0;
}

unless ($personalnumber) {
    print "0\r\n";
    exit 0;
}

my $patrons = Koha::Patrons->search({cardnumber => $cardnumber});
my $borrower = $patrons->next;


unless ($borrower) {
    print "0\r\n";
    exit 0;
}

my $borrowernumber   = $borrower->unblessed->{'borrowernumber'};
my $dateexpiry       = $borrower->unblessed->{'dateexpiry'};
my $categorycode     = $borrower->unblessed->{'categorycode'};
my $lost             = $borrower->unblessed->{'lost'};
my $debarredcomment  = $borrower->unblessed->{'debarredcomment'};
my $retval;

my $pnr12 = GetBorrowerAttributeValue($borrowernumber, "PNR12");
my $pnr = GetBorrowerAttributeValue($borrowernumber, "PNR");
my $outfile = '/tmp/auth_offpc.out';                                      # DEBUG
open (OUTFILE, ">$outfile");                                              # DEBUG
my $today = `date +"%Y-%m-%d"`;

if (!(
        ($pnr12 and (($personalnumber eq $pnr12) or ($personalnumber eq substr($pnr12, 2)))) or
        ($pnr   and (($personalnumber eq $pnr) or (substr($personalnumber, 2) eq $pnr))))) {
    $retval = 0;
}
elsif ($dateexpiry < $today)                               {    $retval = 0; }
elsif ($cardnumber eq $personalnumber )                    {    $retval = 0; }
elsif ($categorycode !~ m/(EX)|(SR)|(FR)|(UX)|(FX)|(NX)/ ) {    $retval = 0; }
elsif ($lost==1)                                           {    $retval = 0; }
elsif ($debarredcomment =~ m/(GU,)|(AV,)/)                 {    $retval = 0; }
else                                                       {    $retval = 1; }
print $retval . "\r\n";
# -------------------------------------------------- #                    # DEBUG
# DEBUG                                              #                    # DEBUG
# -------------------------------------------------- #                    # DEBUG
print OUTFILE "borrowernumber :$borrowernumber: \n";                      # DEBUG
print OUTFILE "dateexpiry     :$dateexpiry:     \n";                      # DEBUG
print OUTFILE "today          :$today           \n";                      # DEBUG
print OUTFILE "categorycode   :$categorycode:   \n";                      # DEBUG
print OUTFILE "pnr            :$pnr:            \n";                      # DEBUG
print OUTFILE "debarredcomment:$debarredcomment:\n";                      # DEBUG
print OUTFILE "lost           :$lost:           \n";                      # DEBUG
print OUTFILE "# ----borrower start-------------------------------- #\n"; # DEBUG
print "\nborrowernumber :$borrowernumber:\n";                             # DEBUG
print "dateexpiry     :$dateexpiry:      \n";                             # DEBUG
print "today          :$today:           \n";                             # DEBUG
print "categorycode   :$categorycode:    \n";                             # DEBUG
print "pnr            :$pnr:             \n";                             # DEBUG
print "debarredcomment:$debarredcomment: \n";                             # DEBUG
print "lost           :$lost:            \n";                             # DEBUG
print OUTFILE Dumper($borrower);                                          # DEBUG
close OUTFILE;                                                            # DEBUG
# -------------------------------------------------- #                    # DEBUG
# DEBUG end                                          #                    # DEBUG
# -------------------------------------------------- #                    # DEBUG


exit 0;
