#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use XML::Simple;
use C4::Auth qw/check_api_auth/;

use C4::Members;
use C4::Members::Attributes qw( CheckUniqueness );

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

# Assume 12 digit personalnumber
my $personalnumber = $query->param('personalnumber');

my $uniq = "false";
if ((CheckUniqueness("PNR", $personalnumber) == 1) and (CheckUniqueness("PNR", substr($personalnumber, 2)) == 1)) {
  $uniq = "true";
}

print $query->header(-type => 'text/xml',-charset => 'utf-8');
print XMLout({uniq => $uniq}, NoAttr => 1, RootName => 'response', XMLDecl => 1);
