#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use XML::Simple;
use C4::Auth qw/check_api_auth/;

use C4::Members;
use C4::Members::Attributes qw( SetBorrowerAttributes );

use Koha::Patron::Debarments;

use Data::Dumper;
my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my %borrower = ();

my $personalnumber = $query->param('personalnumber');

# Mandatory fields
$borrower{'cardnumber'} = $personalnumber;
$borrower{'password'} = $personalnumber;
$borrower{'categorycode'} = $query->param('categorycode');
$borrower{'branchcode'} = $query->param('branchcode');
$borrower{'surname'} = $query->param('surname');
$borrower{'address'} = $query->param('address');
$borrower{'city'} = $query->param('city');

# Optional fields
my $firstname = $query->param('firstname');
if ($firstname) {
  $borrower{'firstname'} = $firstname;
}
my $address2 = $query->param('address2');
if ($address2) {
  $borrower{'address2'} = $address2;
}
my $zipcode = $query->param('zipcode');
if ($zipcode) {
  $borrower{'zipcode'} = $zipcode;
}
my $b_address = $query->param('B_address');
if ($b_address) {
  $borrower{'B_address'} = $b_address;
}
my $b_address2 = $query->param('B_address2');
if ($b_address2) {
  $borrower{'B_address2'} = $b_address2;
}
my $b_city = $query->param('B_city');
if ($b_city) {
  $borrower{'B_city'} = $b_city;
}
my $b_zipcode = $query->param('B_zipcode');
if ($b_zipcode) {
  $borrower{'B_zipcode'} = $b_zipcode;
}
my $phone = $query->param('phone');
if ($phone) {
  $borrower{'phone'} = $phone;
}
my $mobile = $query->param('mobile');
if ($mobile) {
  $borrower{'mobile'} = $mobile;
}
my $email = $query->param('email');
if ($email) {
  $borrower{'email'} = $email;
}

# Patron attribute fields
my $accept_text = $query->param('accept_text');



my ($borrowernumber, $password) = AddMember_Opac(%borrower);

SetBorrowerAttributes($borrowernumber, [{code => "PNR", value => $personalnumber}, {code => "ACCEPT", value => $accept_text}]);

AddDebarment({borrowernumber => $borrowernumber, type => "MANUAL", comment => "WR, Webbregistrerad"});

#C4::Form::MessagingPreferences::handle_form_action($cgi, { borrowernumber => $borrowernumber }, $template, 1, C4::Context->preference('PatronSelfRegistrationDefaultCategory') ) if $borrowernumber && C4::Context->preference('EnhancedMessagingPreferences');

print $query->header(-type => 'text/xml',-charset => 'utf-8', -status => '201');
print XMLout({ borrownumber => $borrowernumber }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
