#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use XML::Simple;
use C4::Auth qw/check_api_auth/;

use C4::Members;
use C4::Members::Attributes qw( SetBorrowerAttributes );

use Koha::Patron::Debarments;
use C4::Members::Messaging;

use Data::Dumper;
my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

my %borrower = ();

my $personalnumber = $query->param('personalnumber');
my $cardnumber = $query->param('cardnumber');
my $messaging_format = $query->param('messaging_format');
my $debarments = $query->param('debarments');

my $origin = $query->param('origin');

if ($cardnumber) {
  $borrower{'cardnumber'} = $cardnumber;
}
else {
  $borrower{'cardnumber'} = $personalnumber;
}

# Mandatory borrower fields
$borrower{'password'} = $personalnumber;
$borrower{'categorycode'} = $query->param('categorycode');
$borrower{'branchcode'} = $query->param('branchcode');
$borrower{'surname'} = $query->param('surname');
$borrower{'address'} = $query->param('address');
$borrower{'city'} = $query->param('city');
$borrower{'lang'} = $query->param('lang');

# Optional fields
my $patronuserid = $query->param('patronuserid');
  if ($patronuserid) {
  $borrower{'userid'} = $patronuserid;
}
my $firstname = $query->param('firstname');
if ($firstname) {
  $borrower{'firstname'} = $firstname;
}
my $address2 = $query->param('address2');
if ($address2) {
  $borrower{'address2'} = $address2;
}
my $zipcode = $query->param('zipcode');
if ($zipcode) {
  $borrower{'zipcode'} = $zipcode;
}
my $country = $query->param('country');
if ($country) {
  $borrower{'country'} = $country;
}
my $b_address = $query->param('B_address');
if ($b_address) {
  $borrower{'B_address'} = $b_address;
}
my $b_address2 = $query->param('B_address2');
if ($b_address2) {
  $borrower{'B_address2'} = $b_address2;
}
my $b_zipcode = $query->param('B_zipcode');
if ($b_zipcode) {
  $borrower{'B_zipcode'} = $b_zipcode;
}
my $b_city = $query->param('B_city');
if ($b_city) {
  $borrower{'B_city'} = $b_city;
}
my $b_country = $query->param('B_country');
if ($b_country) {
  $borrower{'B_country'} = $b_country;
}
my $phone = $query->param('phone');
if ($phone) {
  $borrower{'phone'} = $phone;
}
my $mobile = $query->param('mobile');
if ($mobile) {
  $borrower{'mobile'} = $mobile;
}
my $smsalertnumber = $query->param('smsalertnumber');
if ($smsalertnumber) {
  $borrower{'smsalertnumber'} = $smsalertnumber;
}
my $email = $query->param('email');
if ($email) {
  $borrower{'email'} = $email;
}

# Patron attribute fields
my $accept_text = $query->param('accept_text');

my @debarments;
if ($debarments) {
  @debarments = split /,/, $debarments;
}
if ("gna" ~~ @debarments) {
  $borrower{'gonenoaddress'} = 1;
}


my ($borrowernumber, $password) = AddMember_Opac(%borrower);

if ($origin and $origin eq "gukort") {
  SetBorrowerAttributes($borrowernumber, [{code => "PNR12", value => $personalnumber}, {code => "PNR", value => substr($personalnumber, 2)}, {code => "ACCEPT", value => $accept_text}, {code => "IMPORT", value => "gukort"}]);
}
else {
  SetBorrowerAttributes($borrowernumber, [{code => "PNR12", value => $personalnumber}, {code => "PNR", value => substr($personalnumber, 2)}, {code => "ACCEPT", value => $accept_text}]);
}

foreach my $debarment (@debarments) {
  if ($debarment eq 'wr') {
    AddDebarment({borrowernumber => $borrowernumber, type => "MANUAL", comment => "WR, Webbregistrerad"});
  }
  elsif ($debarment eq 'gu') {
    AddDebarment({borrowernumber => $borrowernumber, type => "MANUAL", comment => "GU, GU-spärr"});
  }
}


# Set messaging format if parameter is set
if ($messaging_format) {
  my $messaging_options = C4::Members::Messaging::GetMessagingOptions();
  my %whichActionsToTickUsingSimpleOpacMessaging = map { $_ => 1 } (split /\|/, C4::Context->preference('whichActionsToTickUsingSimpleOpacMessaging')); # split the string to array and then convert to hash to use keys for easy checking
  foreach my $messaging_option (@{$messaging_options}) {
    if ($whichActionsToTickUsingSimpleOpacMessaging{$messaging_option->{'message_name'}}) {
      if ($messaging_format eq 'sms_email') {
        C4::Members::Messaging::SetMessagingPreference({borrowernumber => $borrowernumber, message_attribute_id => $messaging_option->{'message_attribute_id'}, message_transport_types => ["sms", "email"]});
      }
      else {
        C4::Members::Messaging::SetMessagingPreference({borrowernumber => $borrowernumber, message_attribute_id => $messaging_option->{'message_attribute_id'}, message_transport_types => [$messaging_format]});
      }
    }
  }
}

print $query->header(-type => 'text/xml',-charset => 'utf-8', -status => '201');
print XMLout({ borrownumber => $borrowernumber }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
