#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use C4::Auth qw/check_api_auth/;
use C4::Members;
use C4::Reserves;
use Koha::Patrons;
use C4::Circulation qw(CanBookBeRenewed);
use XML::Simple;
use JSON qw( to_json );

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}
my $userid= $query->url_param('borrower');
my $patrons = Koha::Patrons->search({userid => $userid});
my $borrower = $patrons->next;

unless ($borrower) {
  $patrons = Koha::Patrons->search({cardnumber => $userid});
  $borrower = $patrons->next;
}

#unless ($borrower) {
#  print $query->header(-type => 'text/xml', -status => '404 Not found');
#  print XMLout({ status => 'Borrower not found', error_code => 'borrowerNotFound' }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
#  exit 0;
#}

unless ($borrower) {
  print $query->header(-type => 'application/json', -status => '404 Not found');
  print to_json({ status => 'Borrower not found', error_code => 'borrowerNotFound' });
  exit 0;
}

my $flags = C4::Members::patronflags($borrower->unblessed);
my $borrowernumber = $borrower->unblessed->{'borrowernumber'};
my $attributes = $borrower->extended_attributes;
my $debarments = $borrower->restrictions;
my $message_prefs = C4::Members::Messaging::GetMessagingPreferences({borrowernumber => $borrowernumber, message_name => 'Advance_Notice'});
my @message_preferences = (keys %{$message_prefs->{transports}});

my $opacnorenewal_auto_renewal_blocked = C4::Context->preference("OPACFineNoRenewalsBlockAutoRenew");
my $opacnorenewal_amount = C4::Context->preference("OPACFineNoRenewals");
my $norenewals = 0;
my $noautorenewals = 0;

if($flags->{CHARGES}) {
    if($flags->{CHARGES}->{amount} > $opacnorenewal_amount) {
        $norenewals = 1;
	if($norenewals && $opacnorenewal_auto_renewal_blocked == "1") {
            $noautorenewals = 1;
        }
    }
    $flags->{CHARGES}->{norenewals} = $norenewals;
    $flags->{CHARGES}->{noautorenewals} = $noautorenewals;
}

print $query->header(-type => 'application/json',-charset => 'utf-8');

print to_json({
flags => $flags,
debarments => $debarments->unblessed,
borrower => $borrower->unblessed,
attributes => $attributes->unblessed,
message_preference => \@message_preferences
});

exit 0;

