#!/usr/bin/perl

use strict;
use warnings;
use utf8;

use CGI qw ( -utf8 );
use JSON;
use C4::Auth qw/check_api_auth/;
use C4::Items;

my $query = new CGI;

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/json', -status => '403 Forbidden');
  print encode_json({status => $status});
  exit 0;
}

my $biblionumber = $query->param('biblionumber');

unless ($biblionumber) {
  print $query->header(-type => 'text/json', -status => '400');
  print encode_json({status => 'Biblionumber is required', error_code => 'biblionumberIsMissing'});
  exit 0;
}

my @items = C4::Items::GetItemsInfo( $biblionumber );

print $query->header(-type => 'text/json',-charset => 'utf-8');
print encode_json({items => \@items});
exit 0;
