#!/usr/bin/perl

use strict;
use warnings;

use CGI qw ( -utf8 );
use C4::Auth qw/check_api_auth/;
use Koha::Libraries;
use Koha::Template::Plugin::Branches;
use XML::Simple;

my $query = new CGI;
binmode STDOUT, ':encoding(UTF-8)';

my ($status, $cookie, $sessionID) = check_api_auth($query, { editcatalogue => 'edit_catalogue'} );
unless ($status eq "ok") {
  print $query->header(-type => 'text/xml', -status => '403 Forbidden');
  print XMLout({ status => $status }, NoAttr => 1, RootName => 'response', XMLDecl => 1);
  exit 0;
}

#my $branches = Koha::Template::Plugin::Branches::all();

my @branches = Koha::Libraries->search( {}, { order_by => ['branchname'] }, );
my @list;


foreach my $branch (@branches) {
    #    die(Dumper($branch->unblessed));
    my $br = $branch->unblessed;

    #    my @categories = $branch->get_categories();
    #    my @cats = map { $_->categorycode } @categories;


    my @categories = ();
    my $groups = $branch->library_groups()->as_list;
    foreach my $group (@$groups) {
        push(@categories, $group->parent()->description());
    }


    push(@list, {
        "branchname" => $br->{'branchname'},
        "branchcode" => $br->{'branchcode'},
        "categories" => \@categories
         });
}

print $query->header(-type => 'text/xml',-charset => 'utf-8');

print XMLout({ branches => \@list }, NoAttr => 1, RootName => 'response', XMLDecl => 1);

exit 0;
